version: '2'
services:
    appmcdo-app:
        image: appmcdo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://appmcdo-mysql:3306/appmcdo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    appmcdo-mysql:
        extends:
            file: mysql.yml
            service: appmcdo-mysql
